[package]
name = "trabalho-lp"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
aes-gcm = "0.10"  
aes = "0.6"  
hex = "0.4" 
hex-literal = "0.3"
block-modes = "0.7"
block-cipher = "0.8"
block-padding = "0.2.1"
rand = "0.8"
